### ISSUE TITLE
想请教下你怎么刷istore openwrt

### ISSUE THREAD

**Issue by Manweill** [gofee199/stationP2#1]
老哥，我想请教下你，是怎么把istore刷进去stationP2的，我通过EMMC刷进去了但是启动不了

**Comment by gofee199** [comment]
通过Etcher把固件写入内存卡，然后把卡装到设备上，开机选择从SD卡启动，会卡死在启动界面（没关系），把设备断电或强制关机，再开机，这次进入引导高级菜单，把引导功能删除，等待几秒，强制关机，再开机就进istoreos了

**Comment by gofee199** [comment]
这样做目的是为了让设备默认从SD卡启动，至于为什么用引导进不去我也不知道啥原因。
这样做还有个好处，把内存卡拔了就启动emmc的系统，插上就启动SD的系统

**Comment by Manweill** [comment]
主要是我想直接刷到emmc
